path:
  data: /data/data
  logs: /data/log
  plugins: /data/plugins
  work: /data/work

# Cluster information
cluster.name: <application_name>
node.name: <application_name>

# Security settings
script.disable_dynamic: true

# Index settings
action.auto_create_index: false

# Turn off swap to get a big speed increase.  This will prevent the ES server
# from swapping memory on the node. https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#setup-configuration-memory
bootstrap.mlockall: false

# Disable deleting all indices from the api.
action.disable_delete_all_indices: true

indices.cluster.send_refresh_mapping: false
